name: Docker build and push

on:
  schedule:
    - cron: "0 0 1 * *" # Update monthly
  push:
    branches:
      - main
    paths:
      - "images/**/*"
      - ".github/workflows/ci.yml"
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - target: minimal
            tags: |
              ${{ vars.DOCKER_USERNAME }}/${{ vars.IMAGE_NAME }}:minimal
              ${{ vars.GHCR_PATH }}/${{ vars.IMAGE_NAME }}:minimal
          - target: extended
            tags: |
              ${{ vars.DOCKER_USERNAME }}/${{ vars.IMAGE_NAME }}:extended
              ${{ vars.GHCR_PATH }}/${{ vars.IMAGE_NAME }}:extended
              ${{ vars.DOCKER_USERNAME }}/${{ vars.IMAGE_NAME }}:latest
              ${{ vars.GHCR_PATH }}/${{ vars.IMAGE_NAME }}:latest

    steps:
      - uses: actions/checkout@v3

      # To build arm64 images on x86_64 host, use QEMU.
      - name: Setup QEMU
        uses: docker/setup-qemu-action@v2

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2

      # See https://github.com/docker/login-action#github-container-registry
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: ./images/${{ matrix.target }}
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ matrix.tags }}
